# Site settings
title: Bertrand Pestre
email: bertrand.pestre@gmail.com
url: https://bpestre.github.io
description: "Clean code, healthy mind."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: bertrandpestre.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/bertrandpestre/
  - title: github
    url: https://github.com/bertrandp
  - title: stack-overflow
    url: https://stackoverflow.com/users/5142882/bertrand-pestre

# Build settings
markdown: kramdown
permalink: pretty
