# Site settings
title: Bertrand Pestre
email: bertrandpestre@gmail.com
url: https://bpestre.github.io
description: "Simplicity is the key."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: bertrandpestre.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/bertrandpestre/
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/bertrand-pestre
  - title: github
    url: https://github.com/bertrandp

# Build settings
markdown: kramdown
permalink: pretty
